name: flight_automation_system
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.0.0+3
  path: ^1.8.1
  shared_preferences: ^2.0.6
  encrypted_shared_preferences: ^3.0.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  dartdoc: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/en.json
    - assets/translations/fr.json
    - assets/background.jpg
    - assets/background1.jpg
    - assets/background2.jpg
    - assets/background3.jpg
    - assets/background4.jpg
    - assets/airline_logo.png
